#
# spec file for package samtools
#
# Copyright (c) 2013 Mario Giovacchini <mario@scilifelab.se>
#
# All modifications and additions to the file contributed by third parties
# remain the property of their copyright owners, unless otherwise agreed
# upon. The license for this file, and modifications and additions to the
# file, is the same license as for the pristine package itself (unless the
# license for the pristine package is not an Open Source License, in which
# case the license is the MIT License). An "Open Source License" is a
# license that conforms to the Open Source Definition (Version 1.9)
# published by the Open Source Initiative.

# Please submit bugfixes or comments via http://bugs.opensuse.org/
#

Name:		samtools
Version:	0.1.19
Release:	1%{?dist}
Summary:	A set of tools for processing / filtering SAM- and BAM-formatted data

Group:		Productivity/Scientific/Other
License:	MIT
URL:		http://samtools.sourceforge.net/
Source:		http://sourceforge.net/projects/samtools/files/samtools/%{version}/samtools-%{version}.tar.bz2/download
BuildRoot:	%{_tmppath}/%{name}-%{version}-build

BuildRequires:	zlib
BuildRequires:	ncurses


%description
SAM (Sequence Alignment/Map) format is a generic format for storing large nucleotide sequence alignments. SAM aims to be a format that:

- Is flexible enough to store all the alignment information generated by various alignment programs;
- Is simple enough to be easily generated by alignment programs or converted from existing alignment formats;
- Is compact in file size;
- Allows most of operations on the alignment to work on a stream without loading the whole alignment into memory;
- Allows the file to be indexed by genomic position to efficiently retrieve all reads aligning to a locus.

SAM Tools provide various utilities for manipulating alignments in the SAM format, including sorting, merging, indexing and generating alignments in a per-position format.

%prep
%setup -q

%build
make %{?_smp_mflags}
make %{?_smp_mflags} razip


%install
mkdir -p %{buildroot}%{_bindir}
mkdir -p %{buildroot}%{_libdir}
mkdir -p %{buildroot}%{_includedir}/bam
cp samtools %{buildroot}%{_bindir}/samtools
cp bcftools/bcftools %{buildroot}%{_bindir}/bcftools
cp razip %{buildroot}%{_bindir}/razip
cp libbam.a %{buildroot}%{_libdir}/libbam.a
cp *.h %{buildroot}%{_includedir}/bam/

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%{_bindir}/*
%{_libdir}/libbam.a
%{_includedir}/bam

%changelog
* Thu Nov 28 2013 Mario Giovacchini <mario@scilifelab.se> - 1.1
- Update to include installation of header files and libbam.a
* Tue Nov 19 2013 Mario Giovacchini <mario@scilifelab.se> - 1.0
- Intial version
